In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
train = pd.read_csv('/content/drive/My Drive/DMG/Assignment 3/training.csv')
train

          id         Elevation  ... Horizontal_Distance_To_Fire_Points Label
0          0  elevation_medium  ...                               high     5
1          1  elevation_medium  ...                               high     5
2          2    elevation_high  ...                               high     2
3          3    elevation_high  ...                               high     2
4          4  elevation_medium  ...                               high     5
...      ...               ...  ...                                ...   ...
10995  10995  elevation_medium  ...                                low     3
10996  10996  elevation_medium  ...                                low     6
10997  10997  elevation_medium  ...                                low     3
10998  10998  elevation_medium  ...                                mid     3
10999  10999  elevation_medium  ...                                low     6

[11000 rows x 12 columns]